/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewapc;

import javafx.scene.paint.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class frameAplikasiSewaPC extends javax.swing.JFrame {
    // untuk data PC
    String[] JudulPC = {"No PC","Merek PC","Jenis", "Harga","Stok"};
    int[] LebarKolomPC = {100,270,150,150,100};
    String SQLPC ="SELECT*FROM pc";
    
    // untuk data member
    String[] JudulMember = {"ID Member","Nama Lengkap","Jenis Kelamin", "Alamat","Telepon","Email"};
    int[] LebarKolomMember = {100,200,120,200,120,120};
    String SQLMember ="SELECT*FROM member";

    // untuk data transaksi
    String[] JudulTransaksi = {"ID Sewa","ID Member","Nama Member","No PC","Merek", "Harga", "Jumlah Hari","Biaya"};
    int[] LebarKolomTransaksi = {100,100,200,100,200,150,100,150};
    String SQLTransaksi ="SELECT transaksi_sewa.id_sewa,transaksi_sewa.id_member,member.nama_lengkap,transaksi_sewa.no_pc,pc.merek,pc.harga,transaksi_sewa.jumlah_hari,transaksi_sewa.biaya FROM transaksi_sewa inner join member ON (transaksi_sewa.id_member=member.id_member) inner join pc ON (transaksi_sewa.no_pc=pc.no_pc)";
    /**
     * Creates new form frameAplikasiSewaPC
     */
    public frameAplikasiSewaPC() {
        initComponents();
        new configDB().setJudulKolom(tabelPC, JudulPC);
        new configDB().setTampilTabel(tabelPC, JudulPC, SQLPC);
        new configDB().setLebarJudulKolom(tabelPC, LebarKolomPC);
        
        new configDB().setJudulKolom(tabelMember, JudulMember);
        new configDB().setTampilTabel(tabelMember, JudulMember, SQLMember);
        new configDB().setLebarJudulKolom(tabelMember, LebarKolomMember);
        
        new configDB().setJudulKolom(tabelTransaksi, JudulTransaksi);
        new configDB().setTampilTabel(tabelTransaksi, JudulTransaksi, SQLTransaksi);
        new configDB().setLebarJudulKolom(tabelTransaksi, LebarKolomTransaksi);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel62 = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        buttonPC = new javax.swing.JButton();
        buttonTransaksi = new javax.swing.JButton();
        buttonMember = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        buttonBeranda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        panelBeranda = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        panelPC = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtMerekPC = new javax.swing.JTextField();
        txtJenisPC = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtHargaPC = new javax.swing.JTextField();
        txtStokPC = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtNoPC = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        buttonCetakPC = new javax.swing.JButton();
        buttonBatalPC = new javax.swing.JButton();
        buttonUbahPC = new javax.swing.JButton();
        buttonHapusPC = new javax.swing.JButton();
        buttonTambahPC = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtCariPC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPC = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        panelMember = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtTelpMember = new javax.swing.JTextField();
        txtAlamatMember = new javax.swing.JTextField();
        txtNamaMember = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txtEmailMember = new javax.swing.JTextField();
        comboJKMember = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtIDMember = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtCariMember = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelMember = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        buttonTambahMember = new javax.swing.JButton();
        buttonUbahMember = new javax.swing.JButton();
        buttonHapusMember = new javax.swing.JButton();
        buttonBatalMember = new javax.swing.JButton();
        buttonCetakMember = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        panelTransaksi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtBiayaTransaksi = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txtIDSewaTransaksi = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtIDMemberTransaksi = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        txtCariTransaksi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel57 = new javax.swing.JLabel();
        buttonTambahTransaksi = new javax.swing.JButton();
        buttonUbahTransaksi = new javax.swing.JButton();
        buttonHapusTransaksi = new javax.swing.JButton();
        buttonBatalTransaksi = new javax.swing.JButton();
        buttonCetakTransaksi = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        txtHargaPCTransaksi = new javax.swing.JTextField();
        txtJumlahTransaksi = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txtNoPCTransaksi = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();

        jLabel62.setText("jLabel62");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Smart-Brain");

        panelHeader.setBackground(new java.awt.Color(255, 153, 0));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Forte", 1, 34)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 204, 255));
        jLabel7.setText("SMART-BRAIN");
        panelHeader.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jLabel12.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Aplikasi Sewa PC Banjarbaru");
        panelHeader.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jalan Cukrokusumo KM.404 Loktabet Selatan Banjarbaru, Kalimantan Selatan");
        panelHeader.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backTekno.jpg"))); // NOI18N
        jLabel1.setText("A");
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 80));

        panelMenu.setBackground(new java.awt.Color(255, 153, 70));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel6)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        buttonPC.setBackground(new java.awt.Color(132, 193, 255));
        buttonPC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonPC.setForeground(new java.awt.Color(255, 255, 255));
        buttonPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pc.png"))); // NOI18N
        buttonPC.setText("Data PC");
        buttonPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPC.setName(""); // NOI18N
        buttonPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPCActionPerformed(evt);
            }
        });
        panelMenu.add(buttonPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 60));

        buttonTransaksi.setBackground(new java.awt.Color(132, 193, 255));
        buttonTransaksi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        buttonTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buttonTransaksi.png"))); // NOI18N
        buttonTransaksi.setText("Transaksi Sewa");
        buttonTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransaksiActionPerformed(evt);
            }
        });
        panelMenu.add(buttonTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 160, 60));

        buttonMember.setBackground(new java.awt.Color(132, 193, 255));
        buttonMember.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMember.setForeground(new java.awt.Color(255, 255, 255));
        buttonMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user (2).png"))); // NOI18N
        buttonMember.setText("Data Member");
        buttonMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemberActionPerformed(evt);
            }
        });
        panelMenu.add(buttonMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 60));

        buttonLogout.setBackground(new java.awt.Color(255, 0, 0));
        buttonLogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        buttonLogout.setText("Log Out");
        buttonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });
        panelMenu.add(buttonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 160, 60));

        buttonBeranda.setBackground(new java.awt.Color(132, 193, 255));
        buttonBeranda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonBeranda.setForeground(new java.awt.Color(255, 255, 255));
        buttonBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        buttonBeranda.setText("Beranda");
        buttonBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBerandaActionPerformed(evt);
            }
        });
        panelMenu.add(buttonBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backTekno.jpg"))); // NOI18N
        panelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 540));

        panelBody.setBackground(new java.awt.Color(0, 0, 102));
        panelBody.setLayout(new java.awt.CardLayout());

        panelBeranda.setBackground(new java.awt.Color(0, 153, 255));
        panelBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Menu Beranda");
        panelBeranda.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SMART-BRAIN merupakan aplikasi sewa PC Banjarbaru yang telah berkonstibusi di dunia elektronik");
        panelBeranda.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("lebih dari 20 tahun sehingga memiliki tingkat kualitas, pelayanan, kemudahan yang tinggi. Aplikasi ini dapat");
        panelBeranda.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 173, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("digunakan untuk menyewa PC yang berkantor pusat di Banjarbaru.");
        panelBeranda.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 196, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SMART-BRAIN memiliki kantor pusat di Jalan Cukrokusumo KM.404 Loktabet Selatan   Banjarbaru,");
        panelBeranda.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 231, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("kalimantan Selatan. ");
        panelBeranda.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 254, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mengapa Menyewa lebih menguntungkan ?");
        panelBeranda.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 289, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("-   Arus kas lebih ringan tanpa upfront cost");
        panelBeranda.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 312, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("-   Kemudahan upgrade spesifikasi PC");
        panelBeranda.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 335, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("-   Bebas cemas perawatan dan perbaikan PC");
        panelBeranda.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 358, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("-   Tidak ada depresiasi dari investasi aset");
        panelBeranda.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 381, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Media Sosial");
        panelBeranda.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ig.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBeranda.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fb.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBeranda.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel3.setFont(new java.awt.Font("Forte", 1, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SMART-BRAIN");
        panelBeranda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, 40));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelBeranda.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 20));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelBeranda.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 150, 10));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelBeranda.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 60, -1));

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelBeranda.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelBeranda.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelBeranda.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, -1));

        panelBody.add(panelBeranda, "card2");

        panelPC.setBackground(new java.awt.Color(0, 153, 255));
        panelPC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Menu Data PC");
        panelPC.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Merek PC                :");
        panelPC.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtMerekPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMerekPCActionPerformed(evt);
            }
        });
        panelPC.add(txtMerekPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 360, -1));

        txtJenisPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisPCActionPerformed(evt);
            }
        });
        panelPC.add(txtJenisPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 360, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Jenis                      :");
        panelPC.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Harga Sewa Perhari  :");
        panelPC.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtHargaPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaPCActionPerformed(evt);
            }
        });
        panelPC.add(txtHargaPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 360, -1));

        txtStokPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokPCActionPerformed(evt);
            }
        });
        panelPC.add(txtStokPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 360, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Stok                      :");
        panelPC.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_computer-icon-1046.png"))); // NOI18N
        panelPC.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("No                         :");
        panelPC.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtNoPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPCActionPerformed(evt);
            }
        });
        panelPC.add(txtNoPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 360, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelPC.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 720, 190));

        buttonCetakPC.setBackground(new java.awt.Color(132, 193, 255));
        buttonCetakPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        buttonCetakPC.setText("Cetak");
        buttonCetakPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCetakPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakPCActionPerformed(evt);
            }
        });
        panelPC.add(buttonCetakPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 100, 30));

        buttonBatalPC.setBackground(new java.awt.Color(132, 193, 255));
        buttonBatalPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        buttonBatalPC.setText("Batal");
        buttonBatalPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBatalPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalPCActionPerformed(evt);
            }
        });
        panelPC.add(buttonBatalPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 100, 30));

        buttonUbahPC.setBackground(new java.awt.Color(132, 193, 255));
        buttonUbahPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        buttonUbahPC.setText("Ubah");
        buttonUbahPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonUbahPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahPCActionPerformed(evt);
            }
        });
        panelPC.add(buttonUbahPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, 30));

        buttonHapusPC.setBackground(new java.awt.Color(132, 193, 255));
        buttonHapusPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        buttonHapusPC.setText("Hapus");
        buttonHapusPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHapusPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusPCActionPerformed(evt);
            }
        });
        panelPC.add(buttonHapusPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 100, 30));

        buttonTambahPC.setBackground(new java.awt.Color(132, 193, 255));
        buttonTambahPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        buttonTambahPC.setText("Tambah");
        buttonTambahPC.setBorder(null);
        buttonTambahPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTambahPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahPCActionPerformed(evt);
            }
        });
        panelPC.add(buttonTambahPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 30));

        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelPC.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 720, 50));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Cari data berdasarkan no atau merek PC   :");
        panelPC.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txtCariPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariPCActionPerformed(evt);
            }
        });
        txtCariPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPCKeyReleased(evt);
            }
        });
        panelPC.add(txtCariPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 430, -1));

        tabelPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPC);

        panelPC.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 680, 170));

        jLabel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelPC.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 720, 220));

        panelBody.add(panelPC, "card3");

        panelMember.setBackground(new java.awt.Color(0, 153, 255));
        panelMember.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Menu Member");
        panelMember.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nama Lengkap        :");
        panelMember.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Jenis Kelamin          :");
        panelMember.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Alamat                   :");
        panelMember.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("No Telepon            :");
        panelMember.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtTelpMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpMemberActionPerformed(evt);
            }
        });
        panelMember.add(txtTelpMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 360, -1));

        txtAlamatMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatMemberActionPerformed(evt);
            }
        });
        panelMember.add(txtAlamatMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 360, -1));

        txtNamaMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMemberActionPerformed(evt);
            }
        });
        panelMember.add(txtNamaMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 360, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Email                     :");
        panelMember.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        txtEmailMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailMemberActionPerformed(evt);
            }
        });
        panelMember.add(txtEmailMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 360, -1));

        comboJKMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Laki-laki", "Perempuan" }));
        panelMember.add(comboJKMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 360, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_user.png"))); // NOI18N
        panelMember.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("ID Member             :");
        panelMember.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        panelMember.add(txtIDMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 360, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelMember.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 720, 210));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Cari data berdasarkan ID member atau nama lengkap    :");
        panelMember.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        txtCariMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariMemberActionPerformed(evt);
            }
        });
        txtCariMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariMemberKeyReleased(evt);
            }
        });
        panelMember.add(txtCariMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 360, -1));

        tabelMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMemberMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelMember);

        panelMember.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 680, 150));

        jLabel40.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelMember.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 720, 200));

        buttonTambahMember.setBackground(new java.awt.Color(132, 193, 255));
        buttonTambahMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        buttonTambahMember.setText("Tambah");
        buttonTambahMember.setBorder(null);
        buttonTambahMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTambahMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahMemberActionPerformed(evt);
            }
        });
        panelMember.add(buttonTambahMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, 30));

        buttonUbahMember.setBackground(new java.awt.Color(132, 193, 255));
        buttonUbahMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        buttonUbahMember.setText("Ubah");
        buttonUbahMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonUbahMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahMemberActionPerformed(evt);
            }
        });
        panelMember.add(buttonUbahMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 100, 30));

        buttonHapusMember.setBackground(new java.awt.Color(132, 193, 255));
        buttonHapusMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        buttonHapusMember.setText("Hapus");
        buttonHapusMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHapusMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusMemberActionPerformed(evt);
            }
        });
        panelMember.add(buttonHapusMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 100, 30));

        buttonBatalMember.setBackground(new java.awt.Color(132, 193, 255));
        buttonBatalMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        buttonBatalMember.setText("Batal");
        buttonBatalMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBatalMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalMemberActionPerformed(evt);
            }
        });
        panelMember.add(buttonBatalMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 100, 30));

        buttonCetakMember.setBackground(new java.awt.Color(132, 193, 255));
        buttonCetakMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        buttonCetakMember.setText("Cetak");
        buttonCetakMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCetakMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakMemberActionPerformed(evt);
            }
        });
        panelMember.add(buttonCetakMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 100, 30));

        jLabel39.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelMember.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 720, 50));

        panelBody.add(panelMember, "card4");

        panelTransaksi.setBackground(new java.awt.Color(0, 153, 255));
        panelTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Menu Transaksi Sewa");
        panelTransaksi.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Jumlah Hari Sewa:");
        panelTransaksi.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Biaya                 :");
        panelTransaksi.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, -1));

        txtBiayaTransaksi.setEnabled(false);
        txtBiayaTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiayaTransaksiActionPerformed(evt);
            }
        });
        panelTransaksi.add(txtBiayaTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 350, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("ID Sewa            :");
        panelTransaksi.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        panelTransaksi.add(txtIDSewaTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 350, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("No PC               :");
        panelTransaksi.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("ID Member        :");
        panelTransaksi.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtIDMemberTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDMemberTransaksiActionPerformed(evt);
            }
        });
        panelTransaksi.add(txtIDMemberTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 350, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Cari data berdasarkan no PC atau ID member    :");
        panelTransaksi.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 10));

        txtCariTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariTransaksiActionPerformed(evt);
            }
        });
        txtCariTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariTransaksiKeyReleased(evt);
            }
        });
        panelTransaksi.add(txtCariTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 360, -1));

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelTransaksi);

        panelTransaksi.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 680, 170));

        jLabel57.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelTransaksi.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 730, 220));

        buttonTambahTransaksi.setBackground(new java.awt.Color(132, 193, 255));
        buttonTambahTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        buttonTambahTransaksi.setText("Tambah");
        buttonTambahTransaksi.setBorder(null);
        buttonTambahTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahTransaksiActionPerformed(evt);
            }
        });
        panelTransaksi.add(buttonTambahTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 30));

        buttonUbahTransaksi.setBackground(new java.awt.Color(132, 193, 255));
        buttonUbahTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        buttonUbahTransaksi.setText("Ubah");
        buttonUbahTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonUbahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahTransaksiActionPerformed(evt);
            }
        });
        panelTransaksi.add(buttonUbahTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, 30));

        buttonHapusTransaksi.setBackground(new java.awt.Color(132, 193, 255));
        buttonHapusTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        buttonHapusTransaksi.setText("Hapus");
        buttonHapusTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHapusTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusTransaksiActionPerformed(evt);
            }
        });
        panelTransaksi.add(buttonHapusTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 100, 30));

        buttonBatalTransaksi.setBackground(new java.awt.Color(132, 193, 255));
        buttonBatalTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        buttonBatalTransaksi.setText("Batal");
        buttonBatalTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBatalTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalTransaksiActionPerformed(evt);
            }
        });
        panelTransaksi.add(buttonBatalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 100, 30));

        buttonCetakTransaksi.setBackground(new java.awt.Color(132, 193, 255));
        buttonCetakTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        buttonCetakTransaksi.setText("Cetak");
        buttonCetakTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCetakTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakTransaksiActionPerformed(evt);
            }
        });
        panelTransaksi.add(buttonCetakTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 100, 30));

        jLabel58.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelTransaksi.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 730, 50));

        txtHargaPCTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaPCTransaksiActionPerformed(evt);
            }
        });
        panelTransaksi.add(txtHargaPCTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 350, -1));

        txtJumlahTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahTransaksiKeyReleased(evt);
            }
        });
        panelTransaksi.add(txtJumlahTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 350, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Harga                :");
        panelTransaksi.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtNoPCTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPCTransaksiActionPerformed(evt);
            }
        });
        panelTransaksi.add(txtNoPCTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 350, -1));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksiSewa.png"))); // NOI18N
        panelTransaksi.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 160, 170));

        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelTransaksi.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 730, 200));

        panelBody.add(panelTransaksi, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemberActionPerformed
        // remove panel
        panelBody.removeAll();
        panelBody.repaint();
        panelBody.revalidate();
        
        // add panel
        panelBody.add(panelMember);
        panelBody.repaint();
        panelBody.revalidate();
    }//GEN-LAST:event_buttonMemberActionPerformed

    private void buttonTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransaksiActionPerformed
         // remove panel
        panelBody.removeAll();
        panelBody.repaint();
        panelBody.revalidate();
        
        // add panel
        panelBody.add(panelTransaksi);
        panelBody.repaint();
        panelBody.revalidate();
    }//GEN-LAST:event_buttonTransaksiActionPerformed

    private void buttonBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBerandaActionPerformed
        // remove panel
        panelBody.removeAll();
        panelBody.repaint();
        panelBody.revalidate();
        
        // add panel
        panelBody.add(panelBeranda);
        panelBody.repaint();
        panelBody.revalidate();
    }//GEN-LAST:event_buttonBerandaActionPerformed

    private void buttonPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPCActionPerformed
        // remove panel
        panelBody.removeAll();
        panelBody.repaint();
        panelBody.revalidate();
        
        // add panel
        panelBody.add(panelPC);
        panelBody.repaint();
        panelBody.revalidate();

    }//GEN-LAST:event_buttonPCActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin akan keluar?", "PERINGATAN", dialogBtn);
        
        if (dialogResult==0){
            //true condition
            System.exit(0);
        } else {
            //false condition
            }
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void txtMerekPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMerekPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMerekPCActionPerformed

    private void txtJenisPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisPCActionPerformed

    private void txtHargaPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaPCActionPerformed

    private void txtStokPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokPCActionPerformed

    private void txtCariPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariPCActionPerformed

    private void txtTelpMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpMemberActionPerformed

    private void txtAlamatMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatMemberActionPerformed

    private void txtNamaMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMemberActionPerformed

    private void txtCariMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariMemberActionPerformed

    private void txtEmailMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMemberActionPerformed

//======================================PC==============================================        
    
    private void buttonTambahPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahPCActionPerformed
        if (txtNoPC.getText().equals("")){
            JOptionPane.showMessageDialog(null,"No PC Belum diisi");
            txtNoPC.requestFocus();
        }else if (txtMerekPC.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Merek PC Belum diisi");
            txtMerekPC.requestFocus();
        }else if (txtJenisPC.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Jenis PC Belum diisi");
            txtJenisPC.requestFocus();
        }else if(txtHargaPC.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Harga sewa perhari PC Belum diisi");
            txtHargaPC.requestFocus();  
        }else if (txtStokPC.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Stok PC Belum diisi");
             txtStokPC.requestFocus();
        } else if (new configDB().getDuplikasiKey("pc","no_pc",txtNoPC.getText())){
            JOptionPane.showMessageDialog(null,"No PC sudah terdaftar");
        }else{
           // area koding simpan 
           
           String[] FPC = {"no_pc","merek","jenis", "Harga","Stok"};
           String[] isiPC ={txtNoPC.getText(),txtMerekPC.getText(),txtJenisPC.getText(),txtHargaPC.getText(),txtStokPC.getText()};
           new configDB().SimpanDinamis("pc", FPC, isiPC);
           new configDB().setJudulKolom(tabelPC, JudulPC);
           new configDB().setTampilTabel(tabelPC, JudulPC, SQLPC);
           new configDB().setLebarJudulKolom(tabelPC, LebarKolomPC);
           
            txtNoPC.setText("");
            txtMerekPC.setText("");
            txtJenisPC.setText("");
            txtHargaPC.setText("");
            txtStokPC.setText("");
            txtNoPC.requestFocus();

            txtNoPC.enable(true);
        }
    }//GEN-LAST:event_buttonTambahPCActionPerformed

    private void txtNoPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPCActionPerformed

    private void buttonHapusPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusPCActionPerformed
        new configDB().HapusDinamis("pc", "no_pc", txtNoPC.getText());
        new configDB().setJudulKolom(tabelPC, JudulPC);
        new configDB().setTampilTabel(tabelPC, JudulPC, SQLPC);
        new configDB().setLebarJudulKolom(tabelPC, LebarKolomPC);
        
        txtNoPC.setText("");
        txtMerekPC.setText("");
        txtJenisPC.setText("");
        txtHargaPC.setText("");
        txtStokPC.setText("");
        txtNoPC.requestFocus();
        
        txtNoPC.enable(true);        
    }//GEN-LAST:event_buttonHapusPCActionPerformed

    private void buttonUbahPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahPCActionPerformed
        String tNo = txtNoPC.getText();
        String tMerek = txtMerekPC.getText();
        String tJenis = txtJenisPC.getText();
        String tHarga = txtHargaPC.getText();        
        String tStok = txtStokPC.getText();
        
        String[] fieldPC = {"merek","jenis","harga","Stok"};
        String[] isiPC = {tMerek,tJenis,tHarga,tStok};
        
        new configDB().UbahDinamis("pc", "no_pc", tNo, fieldPC, isiPC);
        new configDB().setJudulKolom(tabelPC, JudulPC);
        new configDB().setTampilTabel(tabelPC, JudulPC, SQLPC);
        new configDB().setLebarJudulKolom(tabelPC, LebarKolomPC);
        
        txtNoPC.setText("");
        txtMerekPC.setText("");
        txtJenisPC.setText("");
        txtHargaPC.setText("");
        txtStokPC.setText("");
        txtNoPC.requestFocus();
        
        txtNoPC.enable(true);
    }//GEN-LAST:event_buttonUbahPCActionPerformed

    private void tabelPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPCMouseClicked
        int row = tabelPC.getSelectedRow();
        txtNoPC.setText(tabelPC.getModel().getValueAt(row,0).toString());
        txtMerekPC.setText(tabelPC.getModel().getValueAt(row,1).toString());
        txtJenisPC.setText(tabelPC.getModel().getValueAt(row,2).toString());
        txtHargaPC.setText(tabelPC.getModel().getValueAt(row,3).toString());
        txtStokPC.setText(tabelPC.getModel().getValueAt(row,4).toString());
        
        txtNoPC.enable(false);
    }//GEN-LAST:event_tabelPCMouseClicked

    private void txtCariPCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPCKeyReleased
        String SQLPCCari ="SELECT*FROM pc WHERE no_pc LIKE '%"+txtCariPC.getText()+"%' OR merek LIKE '%"+txtCariPC.getText()+"%' ";
        new configDB().setJudulKolom(tabelPC, JudulPC);
        new configDB().cariData(tabelPC, JudulPC, SQLPCCari);
        new configDB().setLebarJudulKolom(tabelPC, LebarKolomPC);
    }//GEN-LAST:event_txtCariPCKeyReleased

    private void buttonBatalPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalPCActionPerformed
        txtNoPC.setText("");
        txtMerekPC.setText("");
        txtJenisPC.setText("");
        txtHargaPC.setText("");
        txtStokPC.setText("");
        txtNoPC.requestFocus();
        
        txtNoPC.enable(true);
    }//GEN-LAST:event_buttonBatalPCActionPerformed

    private void buttonCetakPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakPCActionPerformed
        new configDB().tampilLaporan("src/laporan/report1.jrxml","SELECT*FROM pc");
    }//GEN-LAST:event_buttonCetakPCActionPerformed

    
    //================================= MEMBER ======================================
    private void buttonTambahMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahMemberActionPerformed
        if (txtIDMember.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ID Member Belum diisi");
            txtIDMember.requestFocus();
        }else if (txtNamaMember.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nama Lengkap Belum diisi");
            txtNamaMember.requestFocus();
        }else if (comboJKMember.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null,"Jenis Kelamin Belum diisi");
            comboJKMember.requestFocus();
        }else if(txtAlamatMember.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Alamat Belum diisi");
            txtAlamatMember.requestFocus();  
        }else if (txtTelpMember.getText().equals("")){
             JOptionPane.showMessageDialog(null,"No Telepon Belum diisi");
             txtTelpMember.requestFocus();
        }else if (txtEmailMember.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Email Belum diisi");
             txtEmailMember.requestFocus();
        }else if (new configDB().getDuplikasiKey("member","id_member",txtIDMember.getText())){
            JOptionPane.showMessageDialog(null,"ID member sudah terdaftar");
        }else{
           // area koding simpan 
           
           String[] FMember = {"id_member","nama_lengkap","jenis_kelamin", "alamat","telp","email"};
           String[] isiMember ={txtIDMember.getText(),txtNamaMember.getText(),comboJKMember.getSelectedItem().toString(),txtAlamatMember.getText(),txtTelpMember.getText(),txtEmailMember.getText()};
           new configDB().SimpanDinamis("member", FMember, isiMember);
           new configDB().setJudulKolom(tabelMember, JudulMember);
           new configDB().setTampilTabel(tabelMember, JudulMember, SQLMember);
           new configDB().setLebarJudulKolom(tabelMember, LebarKolomMember);
           
            txtIDMember.setText("");
            txtNamaMember.setText("");
            comboJKMember.setSelectedItem(" ");
            txtAlamatMember.setText("");
            txtTelpMember.setText("");
            txtEmailMember.setText("");
            txtIDMember.requestFocus();

            txtIDMember.enable(true);
        }
    }//GEN-LAST:event_buttonTambahMemberActionPerformed

    private void buttonUbahMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahMemberActionPerformed
        String tID = txtIDMember.getText();
        String tNama = txtNamaMember.getText();
        String tJK = comboJKMember.getSelectedItem().toString();
        String tAlamat = txtAlamatMember.getText();        
        String tTelp = txtTelpMember.getText();
        String tEmail = txtEmailMember.getText();
        
        String[] fieldMember = {"nama_lengkap","jenis_kelamin","alamat","telp","email"};
        String[] isiMember = {tNama,tJK,tAlamat,tTelp, tEmail};
        
        new configDB().UbahDinamis("member", "id_member", tID, fieldMember, isiMember);
        new configDB().setJudulKolom(tabelMember, JudulMember);
        new configDB().setTampilTabel(tabelMember, JudulMember, SQLMember);
        new configDB().setLebarJudulKolom(tabelMember, LebarKolomMember);
        
        txtIDMember.setText("");
        txtNamaMember.setText("");
        comboJKMember.setSelectedItem(" ");
        txtAlamatMember.setText("");
        txtTelpMember.setText("");
        txtEmailMember.setText("");
        txtIDMember.requestFocus();
        
        txtIDMember.enable(true);
    }//GEN-LAST:event_buttonUbahMemberActionPerformed

    private void buttonHapusMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusMemberActionPerformed
        new configDB().HapusDinamis("member", "id_member", txtIDMember.getText());
        new configDB().setJudulKolom(tabelMember, JudulMember);
        new configDB().setTampilTabel(tabelMember, JudulMember, SQLMember);
        new configDB().setLebarJudulKolom(tabelMember, LebarKolomMember);
        
        txtIDMember.setText("");
        txtNamaMember.setText("");
        comboJKMember.setSelectedItem(" ");
        txtAlamatMember.setText("");
        txtTelpMember.setText("");
        txtEmailMember.setText("");
        txtIDMember.requestFocus();
        
        txtIDMember.enable(true);
    }//GEN-LAST:event_buttonHapusMemberActionPerformed

    private void buttonBatalMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalMemberActionPerformed
        txtIDMember.setText("");
        txtNamaMember.setText("");
        comboJKMember.setSelectedItem(" ");
        txtAlamatMember.setText("");
        txtTelpMember.setText("");
        txtEmailMember.setText("");
        txtIDMember.requestFocus();
        
        txtIDMember.enable(true);
    }//GEN-LAST:event_buttonBatalMemberActionPerformed

    private void buttonCetakMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakMemberActionPerformed
        new configDB().tampilLaporan("src/laporan/member.jrxml","SELECT*FROM member");
    }//GEN-LAST:event_buttonCetakMemberActionPerformed

    private void tabelMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMemberMouseClicked
        int row = tabelMember.getSelectedRow();
        txtIDMember.setText(tabelMember.getModel().getValueAt(row,0).toString());
        txtNamaMember.setText(tabelMember.getModel().getValueAt(row,1).toString());
        comboJKMember.setSelectedItem(tabelMember.getModel().getValueAt(row,2).toString());
        txtAlamatMember.setText(tabelMember.getModel().getValueAt(row,3).toString());
        txtTelpMember.setText(tabelMember.getModel().getValueAt(row,4).toString());
        txtEmailMember.setText(tabelMember.getModel().getValueAt(row,5).toString());
        txtIDMember.enable(false);
    }//GEN-LAST:event_tabelMemberMouseClicked

    private void txtCariMemberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariMemberKeyReleased
        String SQLMemberCari ="SELECT*FROM member WHERE id_member LIKE '%"+txtCariMember.getText()+"%' OR nama_lengkap LIKE '%"+txtCariMember.getText()+"%' ";
        new configDB().setJudulKolom(tabelMember, JudulMember);
        new configDB().cariData(tabelMember, JudulMember, SQLMemberCari);
        new configDB().setLebarJudulKolom(tabelMember, LebarKolomMember);
    }//GEN-LAST:event_txtCariMemberKeyReleased

    
    //================================== TRANSAKSI ============================================
    
    private void txtBiayaTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiayaTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiayaTransaksiActionPerformed

    private void txtCariTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariTransaksiActionPerformed

    private void txtCariTransaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariTransaksiKeyReleased
        String SQLPCTransaksi ="SELECT transaksi_sewa.id_sewa,transaksi_sewa.id_member,member.nama_lengkap,transaksi_sewa.no_pc,pc.merek,pc.harga,transaksi_sewa.jumlah_hari,transaksi_sewa.biaya FROM transaksi_sewa inner join member ON (transaksi_sewa.id_member=member.id_member) inner join pc ON (transaksi_sewa.no_pc=pc.no_pc) WHERE transaksi_sewa.no_pc LIKE '%"+txtCariTransaksi.getText()+"%' OR transaksi_sewa.id_member LIKE '%"+txtCariTransaksi.getText()+"%' ";
        new configDB().setJudulKolom(tabelTransaksi, JudulTransaksi);
        new configDB().cariData(tabelTransaksi, JudulTransaksi, SQLPCTransaksi);
        new configDB().setLebarJudulKolom(tabelTransaksi, LebarKolomTransaksi);
    }//GEN-LAST:event_txtCariTransaksiKeyReleased

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        int row = tabelTransaksi.getSelectedRow();
        txtIDSewaTransaksi.setText(tabelTransaksi.getModel().getValueAt(row,0).toString());
        txtIDMemberTransaksi.setText(tabelTransaksi.getModel().getValueAt(row,1).toString());
        txtNoPCTransaksi.setText(tabelTransaksi.getModel().getValueAt(row,3).toString());
        txtHargaPCTransaksi.setText(tabelTransaksi.getModel().getValueAt(row,5).toString());
        txtJumlahTransaksi.setText(tabelTransaksi.getModel().getValueAt(row,6).toString());
        txtBiayaTransaksi.setText(tabelTransaksi.getModel().getValueAt(row,7).toString());
        
        txtIDSewaTransaksi.enable(false);
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void buttonTambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahTransaksiActionPerformed
        if (txtIDSewaTransaksi.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ID sewa Belum diisi");
            txtIDSewaTransaksi.requestFocus();
        }else if (txtIDMemberTransaksi.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ID member Belum diisi");
            txtIDMemberTransaksi.requestFocus();
        }else if (txtNoPCTransaksi.getText().equals("")){
            JOptionPane.showMessageDialog(null,"No PC Belum diisi");
            txtNoPCTransaksi.requestFocus();
        }else if(txtHargaPCTransaksi.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Harga Belum diisi");
            txtHargaPCTransaksi.requestFocus();  
        }else if (txtJumlahTransaksi.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Jumlah hari Belum diisi");
             txtJumlahTransaksi.requestFocus();
        }else if (txtBiayaTransaksi.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Biaya Belum diisi");
             txtBiayaTransaksi.requestFocus();
        } else if (new configDB().getDuplikasiKey("transaksi_sewa","id_sewa",txtIDSewaTransaksi.getText())){
            JOptionPane.showMessageDialog(null,"ID sewa sudah terdaftar");
        }else{
           // area koding simpan 
           
           String[] FTransaksi = {"id_sewa","id_member","no_pc", "jumlah_hari","biaya"};
           String[] isiTransaksi ={txtIDSewaTransaksi.getText(),txtIDMemberTransaksi.getText(),txtNoPCTransaksi.getText(),txtJumlahTransaksi.getText(),txtBiayaTransaksi.getText()};
           new configDB().SimpanDinamis("transaksi_sewa", FTransaksi, isiTransaksi);
           new configDB().setJudulKolom(tabelTransaksi, JudulTransaksi);
           new configDB().setTampilTabel(tabelTransaksi, JudulTransaksi, SQLTransaksi);
           new configDB().setLebarJudulKolom(tabelTransaksi, LebarKolomTransaksi);
           
            txtIDSewaTransaksi.setText("");
            txtIDMemberTransaksi.setText("");
            txtNoPCTransaksi.setText("");
            txtHargaPCTransaksi.setText("");
            txtJumlahTransaksi.setText("");
            txtBiayaTransaksi.setText("");
            txtIDSewaTransaksi.requestFocus();

            txtIDSewaTransaksi.enable(true);
        }
    }//GEN-LAST:event_buttonTambahTransaksiActionPerformed

    private void buttonUbahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahTransaksiActionPerformed
        String tIDSewa = txtIDSewaTransaksi.getText();
        String tIDMember = txtIDMemberTransaksi.getText();
        String tNoPC = txtNoPCTransaksi.getText();       
        String tJumlah = txtJumlahTransaksi.getText();
        String tBiaya = txtBiayaTransaksi.getText();
        
        String[] fieldTransaksi = {"id_member","no_pc","jumlah_hari","biaya"};
        String[] isiTransaksi = {tIDMember,tNoPC,tJumlah,tBiaya};
        
        new configDB().UbahDinamis("transaksi_sewa", "id_sewa", tIDSewa, fieldTransaksi, isiTransaksi);
        new configDB().setJudulKolom(tabelTransaksi, JudulTransaksi);
        new configDB().setTampilTabel(tabelTransaksi, JudulTransaksi, SQLTransaksi);
        new configDB().setLebarJudulKolom(tabelTransaksi, LebarKolomTransaksi);
        
        txtIDSewaTransaksi.setText("");
        txtIDMemberTransaksi.setText("");
        txtNoPCTransaksi.setText("");
        txtHargaPCTransaksi.setText("");
        txtJumlahTransaksi.setText("");
        txtBiayaTransaksi.setText("");
        txtIDSewaTransaksi.requestFocus();

        txtIDSewaTransaksi.enable(true);
    }//GEN-LAST:event_buttonUbahTransaksiActionPerformed

    private void buttonHapusTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusTransaksiActionPerformed
        new configDB().HapusDinamis("transaksi_sewa", "id_sewa", txtIDSewaTransaksi.getText());
        new configDB().setJudulKolom(tabelTransaksi, JudulTransaksi);
        new configDB().setTampilTabel(tabelTransaksi, JudulTransaksi, SQLTransaksi);
        new configDB().setLebarJudulKolom(tabelTransaksi, LebarKolomTransaksi);
        
        txtIDSewaTransaksi.setText("");
        txtIDMemberTransaksi.setText("");
        txtNoPCTransaksi.setText("");
        txtHargaPCTransaksi.setText("");
        txtJumlahTransaksi.setText("");
        txtBiayaTransaksi.setText("");
        txtIDSewaTransaksi.requestFocus();
        txtIDSewaTransaksi.enable(true);
    }//GEN-LAST:event_buttonHapusTransaksiActionPerformed

    private void buttonBatalTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalTransaksiActionPerformed
        txtIDSewaTransaksi.setText("");
        txtIDMemberTransaksi.setText("");
        txtNoPCTransaksi.setText("");
        txtHargaPCTransaksi.setText("");
        txtJumlahTransaksi.setText("");
        txtBiayaTransaksi.setText("");
        txtIDSewaTransaksi.requestFocus();
        txtIDSewaTransaksi.enable(true);
    }//GEN-LAST:event_buttonBatalTransaksiActionPerformed

    private void buttonCetakTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakTransaksiActionPerformed
        
    }//GEN-LAST:event_buttonCetakTransaksiActionPerformed

    private void txtIDMemberTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMemberTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMemberTransaksiActionPerformed

    private void txtHargaPCTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaPCTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaPCTransaksiActionPerformed

    private void txtNoPCTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPCTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPCTransaksiActionPerformed

    private void txtJumlahTransaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahTransaksiKeyReleased
        int harga = Integer.parseInt(txtHargaPCTransaksi.getText());
        int jumlah = Integer.parseInt(txtJumlahTransaksi.getText());
        int biaya = harga * jumlah;
        txtBiayaTransaksi.setText("" + biaya);
    }//GEN-LAST:event_txtJumlahTransaksiKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameAplikasiSewaPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameAplikasiSewaPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameAplikasiSewaPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameAplikasiSewaPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameAplikasiSewaPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatalMember;
    private javax.swing.JButton buttonBatalPC;
    private javax.swing.JButton buttonBatalTransaksi;
    private javax.swing.JButton buttonBeranda;
    private javax.swing.JButton buttonCetakMember;
    private javax.swing.JButton buttonCetakPC;
    private javax.swing.JButton buttonCetakTransaksi;
    private javax.swing.JButton buttonHapusMember;
    private javax.swing.JButton buttonHapusPC;
    private javax.swing.JButton buttonHapusTransaksi;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonMember;
    private javax.swing.JButton buttonPC;
    private javax.swing.JButton buttonTambahMember;
    private javax.swing.JButton buttonTambahPC;
    private javax.swing.JButton buttonTambahTransaksi;
    private javax.swing.JButton buttonTransaksi;
    private javax.swing.JButton buttonUbahMember;
    private javax.swing.JButton buttonUbahPC;
    private javax.swing.JButton buttonUbahTransaksi;
    private javax.swing.JComboBox<String> comboJKMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelBeranda;
    public javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMember;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPC;
    public javax.swing.JPanel panelTransaksi;
    private javax.swing.JTable tabelMember;
    private javax.swing.JTable tabelPC;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField txtAlamatMember;
    private javax.swing.JTextField txtBiayaTransaksi;
    private javax.swing.JTextField txtCariMember;
    private javax.swing.JTextField txtCariPC;
    private javax.swing.JTextField txtCariTransaksi;
    private javax.swing.JTextField txtEmailMember;
    private javax.swing.JTextField txtHargaPC;
    public javax.swing.JTextField txtHargaPCTransaksi;
    private javax.swing.JTextField txtIDMember;
    public javax.swing.JTextField txtIDMemberTransaksi;
    private javax.swing.JTextField txtIDSewaTransaksi;
    private javax.swing.JTextField txtJenisPC;
    private javax.swing.JTextField txtJumlahTransaksi;
    private javax.swing.JTextField txtMerekPC;
    private javax.swing.JTextField txtNamaMember;
    private javax.swing.JTextField txtNoPC;
    public javax.swing.JTextField txtNoPCTransaksi;
    private javax.swing.JTextField txtStokPC;
    private javax.swing.JTextField txtTelpMember;
    // End of variables declaration//GEN-END:variables
}
